// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.anicert.proto;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.anicert.netty.proto.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string addr = 3;</code>
   * @return The addr.
   */
  String getAddr();
  /**
   * <code>string addr = 3;</code>
   * @return The bytes for addr.
   */
  com.google.protobuf.ByteString
      getAddrBytes();
}
