// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.anicert.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_anicert_netty_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_anicert_netty_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_anicert_netty_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_anicert_netty_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_anicert_netty_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_anicert_netty_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_anicert_netty_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_anicert_netty_proto_StudentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\026cn.anicert.netty.proto\"" +
      "\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResp" +
      "onse\022\020\n\010realname\030\002 \001(\t\"\035\n\016StudentRequest" +
      "\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name" +
      "\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004addr\030\003 \001(\t2\333\001\n\016St" +
      "udentService\022`\n\025GetRealNameByUserName\022!." +
      "cn.anicert.netty.proto.MyRequest\032\".cn.an" +
      "icert.netty.proto.MyResponse\"\000\022g\n\020GetStu" +
      "dentsByAge\022&.cn.anicert.netty.proto.Stud" +
      "entRequest\032\'.cn.anicert.netty.proto.Stud" +
      "entResponse\"\0000\001B\"\n\020cn.anicert.protoB\014Stu" +
      "dentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_anicert_netty_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_anicert_netty_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_anicert_netty_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_cn_anicert_netty_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_anicert_netty_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_anicert_netty_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_cn_anicert_netty_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_anicert_netty_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_anicert_netty_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_cn_anicert_netty_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cn_anicert_netty_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_anicert_netty_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "Addr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
